data:
  datapath: '/scratch3/wan410/operator_learning_data/pino_ns2d/NS_fft_Re500_T4000.npy'
  name: NS2D
  Re: 500
  total_num: 4000
  offset: 0
  n_sample: 100
  time_interval: 1
  nx: 64
  nt: 64
  sub: 1
  sub_t: 1
  shuffle: True
  S2: 64
  T2: 65

model:
  layers: [64, 64, 64, 64]
  modes1: [8, 8, 8]
  modes2: [8, 8, 8]
  modes3: [8, 8, 8]
  fc_dim: 128
  act: gelu

train:
  batchsize: 100
  epochs: 100_001
  milestones: [20_000, 40_000, 60_000, 80_000]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 1.0
  save_dir: /scratch3/wan410/operator_learning_model/Re500-FNO2d-1s-100
  save_name: FNO2d-Re500-1s-100.pt
  data_iter: 1
  eqn_iter: 0


