data:
  datapath: '/scratch3/wan410/operator_learning_data/pino_ns2d/NS_fft_Re500_T4000.npy'
  Re: 500
  total_num: 4000
  offset: 0
  n_sample: 100
  time_interval: 1
  nx: 64
  nt: 64
  sub: 1
  sub_t: 1
  shuffle: True
  S2: 64
  T2: 65

model:
  arch: wavelet3d
  wave: haar
  dim: 512
  depth: 6
  temporal_depth: 2
  patch_size: [4, 4]
  patch_stride: 4
  in_chans: 4
  out_chans: 1
  learnable_scaling_factor: False

train:
  batchsize: 16
  epochs: 100_001
  milestones: [20_000, 40_000, 60_000, 80_000]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 1.0
  save_dir: Re500-Wavelet-100
  save_name: Wavelet-Re500-1s-100.pt
  data_iter: 1
  eqn_iter: 0

log:
  entity: hzzheng-pino
  project: PINO-Operator-Learning
  group: Wavelet-Re500-1s-100
